### ISSUE TITLE
multiple softpotmagic.begin() function for multiple softpot on the same arduino

### ISSUE THREAD

**Issue by MattH1998** [dogtopus/SoftPotMagic#4]
hello,

first, thanks for that library that helped me a lot in my project,
but i still have a problem, i use 3 softpot on my arduino and i want to know how i can apply the fonctions of your library on the 3 of them.
(excuse me if my english isn't that good, i'm french)

Mattéo.

**Comment by dogtopus** [comment]
You can use the `c_SoftPotMagic` class to create your own instances. For example

```c++
c_SoftPotMagic SP1;
c_SoftPotMagic SP2;
c_SoftPotMagic SP3;

void setup() {
  SP1.begin(A0, A1);
  SP2.begin(A2, A3);
  SP3.begin(A4, A5);
}
```

**Comment by MattH1998** [comment]
Thanks a lot for your help ( sorry for the answer time ... )
